version: '3.6'

services:

  pdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 6543:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pdb
    ports:
      - 7070:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ganin.22@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped